### ISSUE TITLE
Dapp loosing connection with Maiar wallet connect after first signing operation on devnet

### ISSUE THREAD

**Issue by mariusgrigoras** [ElrondNetwork/starter-dapp#117]
Reproduced on devnet and using a dapp startup MVP project for BHN (BlackHatNetwork) project. Should be happening the same with the dapp-template.
The root cause might be the bridge used for devnet.
Basically we lose the Maiar app interface and the https://devnet-wallet.elrond.com/unlock/keystore is bring up.

With json everything works as expected.
Also cannot be reproduced on mainnet using the default DM dapp.

**Comment by ViktorCodevix** [comment]
When we login using Maiar directly from the dapp (not through the devnet), after the first callback we are able to send/make transactions and receive confirmation window on the Maiar application (Android), however, if we refresh or go to another page and try to do a call (sendTransaction) from there, it would redirect us to the devnet login link (feels like a problems with CORS or the session is being lost somehow).
.
Here is a video explaining/showing the actual problem with the flow:
https://drive.google.com/file/d/1_-8uIr0iFjWIigyXZB1mWxZjkJWlbxlJ/view?usp=sharing

P.S. Initially, we used the dapp template from https://github.com/ElrondNetwork/dapp-template (of course, updated).

**Comment by mariusgrigoras** [comment]
All fixed now. Thank you!
