### ISSUE TITLE
[Ledger] Using 2nd address index when signing a message for SC API interaction got ed25519: invalid signature

### ISSUE THREAD

**Issue by mariusgrigoras** [ElrondNetwork/starter-dapp#119]
![image](https://user-images.githubusercontent.com/1903675/128749098-d11e283f-41e9-4c7f-8d25-b36f828db603.png)

SC devnet address -> erd1qqqqqqqqqqqqqpgq5q9xku8tds6qc4el2yw9gsgjmqqgvmhmuguqdpgy4z
An ex of successful tx hash -> https://devnet-explorer.elrond.com/transactions/3ea4e26f7605b6ec0ffc8cb6fef16ed591807f80354f7f99db266bec0eaf75cf

**Comment by bogdan-rosianu** [comment]
Hello! 
Thank you for opening this issue. I've been able to reproduce and will come with a fix.

Thanks!

**Comment by mariusgrigoras** [comment]
Hi Bogdan,

This is very appreciated! We're working for a MVP these days and stress testing different flows. 

Kind regards from all bh.network team members!
Marius
