### ISSUE TITLE
Service fee incorectly displayed

### ISSUE THREAD

**Issue by disruptivedigital** [ElrondNetwork/starter-dapp#26]
The Elrond Delegation Manager Dashboard displays an incorrect value (0.02 %) for the DSSC. The correct value should be 7%. 
DSSC address is: erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqz8llllsh6u4jp

Here is the SC call that changed the service fee: changeServiceFee@02bc
https://testnet-explorer.elrond.com/transactions/9234426de13b5fcce50cc3169c1f0be93c035cde5f6068eeda23dcb689c607e1

![image](https://user-images.githubusercontent.com/66871992/107859243-bcd57480-6e40-11eb-9ae7-5c86c5cfe8ac.png)

**Comment by danielailie** [comment]
This issue was fixed in this PR https://github.com/ElrondNetwork/starter-dapp/pull/28

**Comment by danielailie** [comment]
I'll close this as it was fixed in PR https://github.com/ElrondNetwork/starter-dapp/pull/28
