### ISSUE TITLE
Redirect from wallet failing

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/starter-dapp#29]
I tried several scenarios:
A customer delegating
A owner changing stake cap
A owner adding a node

In all of them, once the transaction is signed and executed properly, it tries to go back without success
![photo_2021-02-14_09-04-38](https://user-images.githubusercontent.com/53934875/107871638-c512cb80-6ea3-11eb-8d4e-6542f73f1655.jpg)

**Comment by mihaieremia** [comment]
So the way react routing is working in relation to Apache is like this.

1) All request need to be pointed from Apache to index.html where the React is intercepting the path and redirecting the internal route.

Create a file in /var/www/html with the name .htaccess and add the following code
RewriteEngine on
    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    # Rewrite everything else to index.html to allow html5 state links
    RewriteRule ^ index.html [L]

https://www.malikbrowne.com/blog/using-react-router-with-apache

**Comment by disruptivedigital** [comment]
I confirm this solution is working for me. Thanks!

**Comment by danielailie** [comment]
I will close this issue as the solution was confirmed working

**Comment by ChrissCohn** [comment]
For me it always redirects to the dashboard main site if i refresh the page from within the admin section "URL/owner", or if i did an admin-transaction (like change fees or so)... after returning from the wallet i land on the main dashboard site "URL/dashboard"

**Comment by wdcurry** [comment]
As of a week ago, the admin wallet callback hits root while the client wallets properly hit the DM subfolder.
