### ISSUE TITLE
Undelegate Max value

### ISSUE THREAD

**Issue by Lallement-Kevin** [ElrondNetwork/starter-dapp#30]
The undelegate dashboard should propose an "undelegate all" button to prevent the following error : 
 "invalid value to undelegate - need to undelegate all - do not leave dust behind"

**Comment by mihaieremia** [comment]
Hey this feature is implemented in my recent PR take a look https://github.com/ElrondNetwork/starter-dapp/pull/24

**Comment by mihaieremia** [comment]
The new features are merged :)

**Comment by danielailie** [comment]
This issue was fixed by this PR https://github.com/ElrondNetwork/starter-dapp/pull/24
