### ISSUE TITLE
Contract addresses 

### ISSUE THREAD

**Issue by cncris** [ElrondNetwork/starter-dapp#34]
Hi,

I don't seem to be able on filling in the right steps for DM, only reached the settings to testnet deleation manager and there i can see only what is available in my wallet.

Need clarifications regarding the following infos:
Delegation contract - address from where the EGLD was staked?
Auction contract -  ?
Staking contract - address where EGLD was staked to?

![image](https://user-images.githubusercontent.com/46869828/108604684-ad5daa80-73af-11eb-9c42-e91988e8e565.png)

**Comment by danielailie** [comment]
Hi, 
You don't have to change the auctionContract and the stakingContract. You only need to update the delegation contract address. After you run createNewDelegationContract@00@00 to create your delegation smart contract on the response data you will receive an address. That is the address that you will use for delegation contract after you convert it with this tool (https://slowli.github.io/bech32-buffer/). For more information read this cheatsheet  https://docs.google.com/document/d/15wXAUIHBQmKefFSg5uY_MnKlgrjZ4zHhKCIOTWukfzE/edit
