### ISSUE TITLE
calculateAPR not accounting for no top-up stake

### ISSUE THREAD

**Issue by alexandru-g** [ElrondNetwork/starter-dapp#39]
In the `calculateAPR` function, `networkStake.totalStaked` was equal to `networkStake.activeValidators * stakePerNode` for a few minutes, leading to a division by 0 when calculating `validatorTopUpReward`. It's either one of 2 things:
- There actually was a moment where all nodes were perfectly staked with 2500 xegld (I don't see how since my contract had a positive top-up stake)
- `dapp.apiProvider.getNetworkStake` returned a wrong value for one of those 2 fields

Either way, we should check if there actually is a network top-up stake when calculating `validatorTopUpReward`.

**Comment by danielailie** [comment]
@alexandru-g I just merged a PR for the APR calculation with the fix. If you can look over to see if everything is ok now. 
Thank you :)

**Comment by danielailie** [comment]
The calculation of the APR was updated. I will close this issue now.
