### ISSUE TITLE
Windows npm start is not working due to HTTPS=true

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/starter-dapp#5]
Hi, the command *npm run start* will not run on windows as the *HTTPS=true* will work just for bash env.
For windows, we need 
```
set HTTPS=true
```
Maybe we can replace the start command with a script that will check the OS and apply the right command.

**Comment by mihaieremia** [comment]
https://create-react-app.dev/docs/using-https-in-development/

**Comment by danielailie** [comment]
This was fixed by https://github.com/ElrondNetwork/starter-dapp/pull/68
