### ISSUE TITLE
Delegating using Ledger does not work

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/starter-dapp#51]
Tests with Ledger fail.

Expected behavior:
1. Clicking the Ledger button on the DM to redirect to https://testnet-wallet.elrond.com/unlock/ledger
2. Select the Ledger account
3. Redirect back to the DM with the selected account

Actual behaviour
1. The login is done instantly with a random account that could not be found in the Ledger account list
2. Even if trying with that account the delegation action is not performed

**Comment by arcsoft-ro** [comment]
Just found out that the Wallet button must be used instead.

After the redirection to the Elrond Wallet, the Ledger option must be used.

I will leave this opened to be used maybe for removing the Ledger button from the DM

**Comment by danielailie** [comment]
This was fixed by this PR https://github.com/ElrondNetwork/starter-dapp/pull/63
