### ISSUE TITLE
Usability: Max Delegation Button

### ISSUE THREAD

**Issue by AL-Digital** [ElrondNetwork/starter-dapp#74]
The max delegation button could be improved by:
- considering the gas price and reducing the amount by the gas price
- considering the delegation cap besides the amount available in the wallet when calculating the max

**Comment by danielailie** [comment]
Thank you for the notice. I raised a PR to update the button https://github.com/ElrondNetwork/starter-dapp/pull/77

**Comment by danielailie** [comment]
@AL-Digital The fix was merge into master. Let me know if it is okay now
