### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by ChristianGrenz** [ElrondNetwork/starter-dapp#94]
TypeScript error in /home/ubuntu/starter-dapp/react-delegationdashboard/src/pages/Owner/Nodes/NodeRow.tsx(60,31):
Cannot find name 'value'.  TS2304

60 |       const untypedResponse = value.outputUntyped();

**Comment by danielailie** [comment]
This was fixed by this PR https://github.com/ElrondNetwork/starter-dapp/pull/95
Thank you for raising it
